version: "3.7"

services:
  gns:
    build:
      context: ./gns
    image: gns:1.19.16
    depends_on:
      - mongo
    network_mode: "host"
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb:/data
      - ./mongo/conf:/etc/mongo
    command: "mongod --config /etc/mongo/mongod.conf"

volumes:
  mongodb:
